name: deploy-latest-log
on:
  schedule:
    - cron: '0 */6 * * 1-5'
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MUNICIPALITIES_URL: ${{ secrets.MUNICIPALITIES_URL }}
      NEW_INFECTED_URL: ${{ secrets.NEW_INFECTED_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - name: Move latest tag
        run: |
          tag=`git describe --abbrev=0 --tags`
          git checkout tags/$tag

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm ci --prefer-offline --no-audit


      - name: Update latest number COVID-19
        run: npm run update-log
        run: |
          git config user.name cron-daily-update
          git config user.email cron@cron.com
          git add .
          git commit -m "Add report for today"
          git push
      
      - name: Run build ğŸ—
        run: npm run build

      - name: Run export ğŸš¢
        run: npm run export

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.